[package]
name = "audio-thumbnailer"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
hex_color = "3.0.0"
image = "0.25.1"
plotters = "0.3.5"
symphonia = { version = "0.5.4", features = ["all"] }
symphonia-core = "0.5.4"

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"

[dev-dependencies]
rstest = "0.19.0"
