[cover_settings]
no_cover = false

# size of the generated cover art
# for example size of 64 will generate as 64x64 cover
# when using aspect_ratio auto, size will be used as a smaller side of the rectangle
size = 64

# interpolation algorithm used for scaling the image
# possible options are: "Lanczos3", "CatmullRom", "Gaussian", "Nearest", "Triangle"
interpolation = "Triangle"

# aspect ratio used for image generation
# Auto - keeps the original aspect ratio
# Stretch - strech original image into a square
# Crop - crops the original image, getting rid of the edges
aspect_ratio = "Crop"

# generate a waveform if getting a thumbnail fails
waveform_on_fail = true

# other thumbnailers use some form of overlay on top of the cover
# to make it destinguishable from the other file formats
# therefore, possible options are:
# "cd", "none"
overlay = "none"

# image format used for thumbnails
image_format = "Jpeg"

# disabled by default
# can be enabled by building with "colored_waveform" feature
[audio_analyzer_settings]

fft_enabled = true
fft_size = 1024

[waveform_settings]
# width and height of a generated waveform thumbnail
length = 200
height = 80

# sample_style = bars | line | scatter | spectrum
# sample_smoothing = 1.0
# fill_type = solid | gradient | texture | none
# fill_colors = None
fill_color = "#7ad64d"
# fill_texture = PathBuf
# stroke_type = solid | gradient | texture | none
# stroke_texture = PathBuf
# stroke_color = None
# stroke_colors = None
# stroke_width = None

# disabled by default
# can be enabled by building with "3d_wavetables" feature
[wavetable_settings]
horizontal_rotation = -0.24
vertical_rotation = 1.22
width = 0.72
height = 0.1
y_offset = 0.05

[debug]
enabled = false
log_file = "$DEBUG_PATH"
